version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: olist_postgres
    environment:
      POSTGRES_USER: data_engineer
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: olist
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./seed:/data/seed
    restart: unless-stopped
